### PR TITLE
Fixed onNavigateToPhoto when current photo is nil

### PR DESCRIPTION
**Pull request by RodolfoGS**
Fix this issue: https://github.com/merryjs/photo-viewer/issues/102

### CODE REVIEW

**Comment by bang88** [comment]
@RodolfoGS Have you tested it if so I will publish it a few minutes later.

**Comment by bang88** [comment]
@RodolfoGS 3.1.2

**Comment by RodolfoGS** [comment]
@bang88 Yes, I'm using in production right now since 1 week ago and the error dissapear from Crashlytics. Works perfect.

**Comment by bang88** [comment]
@RodolfoGS Please install the latest version

**Comment by RodolfoGS** [comment]
@bang88 Installed, thank you so much! 👍

**Pull request merged**
