### PR TITLE
Fix RN 0.60+ warnings #78 and #98

### PR DESCRIPTION
**Pull request by vforvasile**
- Switch from require to import;
- use ImageSourcePropType from DeprecatedPropTypes
[issue 78](https://github.com/merryjs/photo-viewer/issues/78)
- use RCTImageLoader class inside MerryPhotoView.m (fix bridge.imageLoader)
[issue 92](https://github.com/merryjs/photo-viewer/issues/92)

### CODE REVIEW

**Comment by bang88** [comment]
Thank you very much. will release it later

**Comment by TrustTheBoy** [comment]
3.1.0 still has this problem

**Comment by vforvasile** [comment]
> 3.1.0 still has this problem

which one?

**Comment by bang88** [comment]
3.1.1 finally published due to the network error.

**Pull request merged**
